image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - pip install pip --upgrade
            - pytest api/companies -s -v --durations=0

