image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - pip install pip --upgrade
            - export PYTHONPATH=$PYTHONPATH:$PYTHONPATH/companies
            - export DJANGO_SETTINGS_MODULE="api.settings"
            - pytest companies -s -v --durations=0

