version: '3.7'

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn api.wsgi:application --bind 0.0.0.0:9000
    volumes:
          - static_volume:/home/app/api/staticfiles
    expose:
      - 9000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_prod_db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - api

volumes:
  postgres_data:
  static_volume:
